# This file was generated by GoReleaser. DO NOT EDIT.
class Potato < Formula
  desc "Potato is a command line tool which helps you to keep the development configs and settings of your Mac as a programmer safe in your GitHub."
  homepage ""
  version "0.1.2"

  if OS.mac?
    url "https://github.com/horcrux2301/Potato/releases/download/v0.1.2/Potato_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "0eff28d710ef4669c3bbbbf5fe55b212c4204d6e310d5d3d9d68274f5e9c6978"
  elsif OS.linux?
    url "https://github.com/horcrux2301/Potato/releases/download/v0.1.2/Potato_0.1.2_Linux_x86_64.tar.gz"
    sha256 "dc35c7c5020fdc1251884aea791241a9d7318ce11c5b71f58f8e784b7e0bbaab"
  end

  def install
    bin.install "Potato"
  end

  test do
    system "#{bin}/Potato --version"
  end
end
